/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: ../sanity.schema.json
export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type AuthorImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "authorImage.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  alt?: string
  _type: 'image'
}

export type Note = {
  _type: 'note'
  tone: 'info' | 'warning' | 'danger'
  icon?:
    | 'information'
    | 'warning'
    | 'error'
    | 'question'
    | 'lightbulb'
    | 'sparkles'
    | 'check'
    | 'bell'
    | 'fire'
    | 'shield'
  content: BlockContentTextOnly
  background?: Background
}

export type Scores = {
  _type: 'scores'
  heading?: string
  caption?: BlockContentTextOnly
  items?: Array<{
    label: string
    value: number
    max?: number
    asPercent?: boolean
    _type: 'score'
    _key: string
  }>
  background?: Background
}

export type Stats = {
  _type: 'stats'
  heading?: string
  subheading?: string
  items?: Array<{
    value: string
    label: string
    description?: string
    _type: 'stat'
    _key: string
  }>
  columns?: 2 | 3 | 4
}

export type Faq = {
  _type: 'faq'
  heading?: string
  subheading?: string
  items?: Array<{
    question: string
    answer?: BlockContentTextOnly
    _type: 'faqItem'
    _key: string
  }>
}

export type Testimonials = {
  _type: 'testimonials'
  heading?: string
  subheading?: string
  testimonials?: Array<{
    quote: string
    authorName: string
    authorRole?: string
    authorImage?: AuthorImage
    _type: 'testimonial'
    _key: string
  }>
  columns?: 1 | 2 | 3
}

export type FeaturesGrid = {
  _type: 'featuresGrid'
  heading?: string
  subheading?: string
  features?: Array<{
    icon?:
      | 'sparkles'
      | 'bolt'
      | 'shield'
      | 'rocket'
      | 'chip'
      | 'cloud'
      | 'code'
      | 'chart'
      | 'cursor'
      | 'globe'
      | 'lock'
      | 'heart'
      | 'star'
      | 'check'
      | 'beaker'
    heading: string
    text?: string
    link?: Link
    _type: 'feature'
    _key: string
  }>
  columns?: 2 | 3 | 4
}

export type GalleryVideo = {
  _type: 'galleryVideo'
  url: string
  title: string
  poster?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  caption?: string
  aspect?: 'square' | 'video' | 'auto'
}

export type Gallery = {
  _type: 'gallery'
  heading?: string
  items?: Array<
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: string
        caption?: string
        _type: 'galleryImage'
        _key: string
      }
    | ({
        _key: string
      } & GalleryVideo)
  >
  layout?: 'grid' | 'masonry' | 'carousel'
  columns?: 2 | 3 | 4
  aspect?: 'square' | 'video' | 'auto'
  enableLightbox?: boolean
}

export type PersonReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'person'
}

export type AuthorsArchive = {
  _type: 'authorsArchive'
  heading?: string
  subheading?: string
  source?: 'all' | 'picked'
  limit?: number
  authors?: Array<
    {
      _key: string
    } & PersonReference
  >
  columns?: 2 | 3 | 4
}

export type CategoryReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'category'
}

export type ProjectReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'project'
}

export type ProjectsArchive = {
  _type: 'projectsArchive'
  heading?: string
  subheading?: string
  source?: 'latest' | 'all' | 'picked'
  limit?: number
  category?: CategoryReference
  projects?: Array<
    {
      _key: string
    } & ProjectReference
  >
  columns?: 2 | 3
  showFilter?: boolean
  showTechFilter?: boolean
  showSort?: boolean
}

export type PostReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'post'
}

export type PostsArchive = {
  _type: 'postsArchive'
  heading?: string
  subheading?: string
  source?: 'latest' | 'all' | 'picked'
  limit?: number
  category?: CategoryReference
  posts?: Array<
    {
      _key: string
    } & PostReference
  >
  columns?: 2 | 3
}

export type Hero = {
  _type: 'hero'
  eyebrow?: string
  heading: string
  lede?: string
  buttons?: Array<
    {
      _key: string
    } & Button
  >
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  layout?: 'center' | 'split'
  theme?: 'light' | 'dark'
}

export type Background = {
  _type: 'background'
  type: 'none' | 'shader'
  preset?: 'blob'
  speed?: number
  intensity?: number
  colorSource?: 'theme' | 'custom'
  customColor?: string
  opacity?: number
}

export type NavDropdown = {
  _type: 'navDropdown'
  title: string
  links?: Array<
    {
      _key: string
    } & NavLink
  >
}

export type NavLink = {
  _type: 'navLink'
  title?: string
  link: Link
}

export type Social = {
  _type: 'social'
  title: string
  platform: 'twitter' | 'instagram' | 'facebook' | 'vimeo' | 'linkedin' | 'github' | 'mastodon'
  url: string
}

export type Contact = {
  _type: 'contact'
  email?: string
  phone?: string
  socials?: Array<
    {
      _key: string
    } & Social
  >
}

export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type Link = {
  _type: 'link'
  linkType?: 'href' | 'page' | 'post'
  href?: string
  page?: PageReference
  post?: PostReference
  openInNewTab?: boolean
}

export type CallToAction = {
  _type: 'callToAction'
  eyebrow?: string
  heading: string
  body?: BlockContentTextOnly
  button?: Button
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  theme?: 'light' | 'dark'
  contentAlignment?: 'textFirst' | 'imageFirst'
  background?: Background
}

export type InfoSection = {
  _type: 'infoSection'
  heading?: string
  subheading?: string
  content?: BlockContent
  background?: Background
}

export type BlockContentTextOnly = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    href?: string
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        linkType?: 'href' | 'page' | 'post'
        href?: string
        page?: PageReference
        post?: PostReference
        openInNewTab?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    }
>

export type Button = {
  _type: 'button'
  buttonText?: string
  link?: Link
}

export type Technology = {
  _id: string
  _type: 'technology'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  url?: string
  description?: string
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type Category = {
  _id: string
  _type: 'category'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  description?: string
}

export type TechnologyReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'technology'
}

export type Project = {
  _id: string
  _type: 'project'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  excerpt?: string
  coverImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  publishedAt?: string
  updatedAt?: string
  website?: string
  repo?: string
  categories?: Array<
    {
      _key: string
    } & CategoryReference
  >
  tech?: Array<
    {
      _key: string
    } & TechnologyReference
  >
  featured?: boolean
  hidden?: boolean
  body?: BlockContent
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type SanityFileAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      linkType?: 'href' | 'page' | 'post'
      href?: string
      page?: PageReference
      post?: PostReference
      openInNewTab?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  logo?: {
    asset?: SanityFileAssetReference
    media?: unknown
    _type: 'file'
  }
  favicon?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
  blurb?: string
  contact?: Contact
  navigation?: Array<
    | ({
        _key: string
      } & NavLink)
    | ({
        _key: string
      } & NavDropdown)
  >
  mobileNav?: {
    showFooterContent?: boolean
  }
  legal?: string
  builtWith?: Array<{
    name: string
    url?: string
    icon?: string
    _type: 'builtWithItem'
    _key: string
  }>
  homepage?: PageReference
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  heading: string
  subheading?: string
  archive?: 'postsArchive' | 'projectsArchive' | 'authorsArchive'
  background?: Background
  pageBuilder?: Array<
    | ({
        _key: string
      } & Hero)
    | ({
        _key: string
      } & CallToAction)
    | ({
        _key: string
      } & InfoSection)
    | ({
        _key: string
      } & FeaturesGrid)
    | ({
        _key: string
      } & Stats)
    | ({
        _key: string
      } & Scores)
    | ({
        _key: string
      } & Testimonials)
    | ({
        _key: string
      } & Gallery)
    | ({
        _key: string
      } & Faq)
    | ({
        _key: string
      } & Note)
    | ({
        _key: string
      } & PostsArchive)
    | ({
        _key: string
      } & ProjectsArchive)
    | ({
        _key: string
      } & AuthorsArchive)
  >
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  content?: BlockContent
  excerpt?: string
  coverImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  date?: string
  author?: PersonReference
  categories?: Array<
    {
      _key: string
    } & CategoryReference
  >
}

export type Person = {
  _id: string
  _type: 'person'
  _createdAt: string
  _updatedAt: string
  _rev: string
  firstName: string
  lastName: string
  picture: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type AssistInstructionContextReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: AssistInstructionContextReference
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type MediaTag = {
  _id: string
  _type: 'media.tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: Slug
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | AuthorImage
  | Note
  | Scores
  | Stats
  | Faq
  | Testimonials
  | FeaturesGrid
  | GalleryVideo
  | Gallery
  | PersonReference
  | AuthorsArchive
  | CategoryReference
  | ProjectReference
  | ProjectsArchive
  | PostReference
  | PostsArchive
  | Hero
  | Background
  | NavDropdown
  | NavLink
  | Social
  | Contact
  | PageReference
  | Link
  | CallToAction
  | InfoSection
  | BlockContentTextOnly
  | BlockContent
  | Button
  | Technology
  | Slug
  | Category
  | TechnologyReference
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | SanityFileAssetReference
  | Settings
  | Page
  | Post
  | Person
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
