/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: ../sanity.schema.json
export type Address = {
  street?: string
  city?: string
  region?: string
  postalCode?: string
  country?: string
}

export type PullQuote = {
  _type: 'pullQuote'
  quote: string
  attribution?: string
  repeatsText?: boolean
  tone?: 'plain' | 'panel'
  anchor?: string
}

export type Note = {
  _type: 'note'
  tone: 'info' | 'warning' | 'danger'
  icon?:
    | 'information'
    | 'warning'
    | 'error'
    | 'question'
    | 'lightbulb'
    | 'sparkles'
    | 'check'
    | 'bell'
    | 'fire'
    | 'shield'
  content: BlockContentTextOnly
  anchor?: string
}

export type Stats = {
  _type: 'stats'
  heading?: string
  subheading?: string
  items?: Array<{
    value: string
    label: string
    description?: string
    _type: 'stat'
    _key: string
  }>
  columns?: 2 | 3 | 4
  anchor?: string
}

export type Faq = {
  _type: 'faq'
  heading?: string
  subheading?: string
  items?: Array<{
    question: string
    answer?: BlockContentTextOnly
    _type: 'faqItem'
    _key: string
  }>
  anchor?: string
}

export type ContactDetails = {
  _type: 'contactDetails'
  heading?: string
  intro?: string
  showHours?: boolean
  showMapLink?: boolean
  secondaryEmail?: string
  anchor?: string
}

export type PersonReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'person'
}

export type FacultyGrid = {
  _type: 'facultyGrid'
  heading?: string
  subheading?: string
  mode?: 'all' | 'selected'
  people?: Array<
    {
      _key: string
    } & PersonReference
  >
  showBio?: boolean
  columns?: 2 | 3 | 4
  anchor?: string
}

export type ProgramReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'program'
}

export type ProgramsGrid = {
  _type: 'programsGrid'
  heading?: string
  subheading?: string
  mode?: 'all' | 'selected'
  programs?: Array<
    {
      _key: string
    } & ProgramReference
  >
  columns?: 2 | 3 | 4
  anchor?: string
}

export type Testimonials = {
  _type: 'testimonials'
  heading?: string
  subheading?: string
  layout?: 'cards' | 'letters'
  featuredOnly?: boolean
  limit?: number
  columns?: 1 | 2 | 3
  anchor?: string
}

export type FeaturesGrid = {
  _type: 'featuresGrid'
  heading?: string
  subheading?: string
  features?: Array<{
    icon?:
      | 'academic'
      | 'book'
      | 'puzzle'
      | 'paint'
      | 'music'
      | 'globe'
      | 'science'
      | 'math'
      | 'idea'
      | 'outdoors'
      | 'care'
      | 'smile'
      | 'independence'
      | 'community'
      | 'home'
      | 'safety'
      | 'schedule'
      | 'calendar'
      | 'apply'
      | 'document'
      | 'talk'
      | 'phone'
      | 'email'
      | 'location'
      | 'check'
    heading: string
    text?: string
    link?: Link
    _type: 'feature'
    _key: string
  }>
  columns?: 2 | 3 | 4
  anchor?: string
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type GalleryVideo = {
  _type: 'galleryVideo'
  url: string
  title: string
  poster?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  caption?: string
  aspect?: 'square' | 'video' | 'auto'
}

export type Gallery = {
  _type: 'gallery'
  heading?: string
  items?: Array<
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: string
        caption?: string
        _type: 'galleryImage'
        _key: string
      }
    | ({
        _key: string
      } & GalleryVideo)
  >
  layout?: 'grid' | 'masonry' | 'carousel' | 'collage'
  columns?: 2 | 3 | 4
  aspect?: 'square' | 'video' | 'auto'
  enableLightbox?: boolean
  anchor?: string
}

export type NavDropdown = {
  _type: 'navDropdown'
  title: string
  links?: Array<
    {
      _key: string
    } & NavLink
  >
}

export type NavLink = {
  _type: 'navLink'
  title?: string
  link: Link
}

export type Social = {
  _type: 'social'
  title: string
  platform: 'twitter' | 'instagram' | 'facebook' | 'vimeo' | 'linkedin'
  url: string
}

export type Seo = {
  _type: 'seo'
  metaTitle?: string
  metaDescription?: string
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  noIndex?: boolean
}

export type Masthead = {
  _type: 'masthead'
  variant: 'brand' | 'image'
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  tone?: 'primary' | 'ink' | 'secondary'
  eyebrow?: string
  showLogo?: boolean
  logoPlacement?: 'center' | 'bottomLeft'
  height?: 'tall' | 'standard' | 'compact'
  overlay?: 'none' | 'light' | 'medium' | 'strong'
  focalNote?: string
}

export type Contact = {
  _type: 'contact'
  email?: string
  phone?: string
  fax?: string
  address?: Address
  hours?: Array<{
    days: string
    time: string
    schemaOrg?: string
    _type: 'hoursRow'
    _key: string
  }>
  mapUrl?: string
  socials?: Array<
    {
      _key: string
    } & Social
  >
}

export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type Link = {
  _type: 'link'
  linkType?: 'page' | 'href'
  page?: PageReference | ProgramReference
  anchor?: string
  href?: string
  openInNewTab?: boolean
}

export type CallToAction = {
  _type: 'callToAction'
  eyebrow?: string
  heading: string
  body?: BlockContentTextOnly
  button?: Button
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  theme?: 'light' | 'brand'
  contentAlignment?: 'textFirst' | 'imageFirst'
  anchor?: string
}

export type InfoSection = {
  _type: 'infoSection'
  heading?: string
  subheading?: string
  content?: BlockContent
  anchor?: string
}

export type BlockContentTextOnly = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    href?: string
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        linkType?: 'page' | 'href'
        page?: PageReference | ProgramReference
        anchor?: string
        href?: string
        openInNewTab?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    }
>

export type Button = {
  _type: 'button'
  buttonText?: string
  link?: Link
}

export type Person = {
  _id: string
  _type: 'person'
  _createdAt: string
  _updatedAt: string
  _rev: string
  firstName: string
  lastName: string
  picture: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  role?: string
  credentials?: Array<string>
  bio?: BlockContentTextOnly
  order?: number
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Testimonial = {
  _id: string
  _type: 'testimonial'
  _createdAt: string
  _updatedAt: string
  _rev: string
  quote: string
  highlight?: string
  authorName: string
  authorRole?: string
  authorImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  featured?: boolean
  order?: number
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      linkType?: 'page' | 'href'
      page?: PageReference | ProgramReference
      anchor?: string
      href?: string
      openInNewTab?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
  blurb?: string
  contact?: Contact
  foundingDate?: string
  areaServed?: Array<string>
  priceRange?: string
  geo?: {
    lat?: number
    lng?: number
  }
  navigation?: Array<
    | ({
        _key: string
      } & NavLink)
    | ({
        _key: string
      } & NavDropdown)
  >
  legal?: string
  homepage?: PageReference
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  heading: string
  subheading?: string
  titleDisplay?: 'plain' | 'highlighted' | 'none'
  masthead?: Masthead
  seo?: Seo
  pageBuilder?: Array<
    | ({
        _key: string
      } & CallToAction)
    | ({
        _key: string
      } & InfoSection)
    | ({
        _key: string
      } & FeaturesGrid)
    | ({
        _key: string
      } & Stats)
    | ({
        _key: string
      } & Testimonials)
    | ({
        _key: string
      } & ProgramsGrid)
    | ({
        _key: string
      } & FacultyGrid)
    | ({
        _key: string
      } & ContactDetails)
    | ({
        _key: string
      } & Gallery)
    | ({
        _key: string
      } & Faq)
    | ({
        _key: string
      } & Note)
    | ({
        _key: string
      } & PullQuote)
  >
}

export type Program = {
  _id: string
  _type: 'program'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  ageRange: string
  ratio?: string
  classroomName?: string
  summary: string
  body?: BlockContent
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  scheduleNote?: string
  order: number
  masthead?: Masthead
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type AssistInstructionContextReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: AssistInstructionContextReference
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type MediaTag = {
  _id: string
  _type: 'media.tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: Slug
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | Address
  | PullQuote
  | Note
  | Stats
  | Faq
  | ContactDetails
  | PersonReference
  | FacultyGrid
  | ProgramReference
  | ProgramsGrid
  | Testimonials
  | FeaturesGrid
  | SanityImageAssetReference
  | GalleryVideo
  | Gallery
  | NavDropdown
  | NavLink
  | Social
  | Seo
  | Masthead
  | Contact
  | PageReference
  | Link
  | CallToAction
  | InfoSection
  | BlockContentTextOnly
  | BlockContent
  | Button
  | Person
  | SanityImageCrop
  | SanityImageHotspot
  | Testimonial
  | Settings
  | Page
  | Program
  | Slug
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
